version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  nosqldata:
    image: mysql

  userdata:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity-api:
    image: documentmonoapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - mysql

 
